# Generated by Django 5.2.6 on 2025-10-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/tmp/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/tmp/')),
                ('category', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('horror', 'Horror'), ('musical', 'Musical'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('war', 'War'), ('western', 'Western'), ('biography', 'Biography'), ('family', 'Family'), ('sport', 'Sport')], default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
