# Generated by Django 5.2.6 on 2025-10-14 08:29

import app_videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=app_videos.models.thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=app_videos.models.video_upload_path),
        ),
    ]
